//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntesQueVenca.Ecommerce.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AntesQueVencaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntesQueVencaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntesQueVenca.Ecommerce.Resources.AntesQueVencaResources", typeof(AntesQueVencaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                  &lt;/table&gt;
        ///                &lt;/td&gt;
        ///              &lt;/tr&gt;
        ///
        ///            &lt;!-- END MAIN CONTENT AREA --&gt;
        ///            &lt;/table&gt;
        ///			&lt;/div&gt;
        ///            &lt;!-- START FOOTER --&gt;
        ///            &lt;div class=&quot;footer&quot; style=&quot;clear: both; Margin-top: 10px; text-align: center; width: 100%;&quot;&gt;
        ///              &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;&quot;&gt;
        ///                &lt;tr&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderConfirmationAfterProducts {
            get {
                return ResourceManager.GetString("OrderConfirmationAfterProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Simple Transactional Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///    /* -------------------------------------
        ///        INLINED WITH htmlemail.io/inline
        ///    ------------------------------------- */
        ///    /* -------------------------------------
        ///        RESPONSIVE AND MOBILE FRIENDLY STYLES
        ///    ------------------------------------- */
        ///    @media onl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderConfirmationBeforeProducts {
            get {
                return ResourceManager.GetString("OrderConfirmationBeforeProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                  &lt;/table&gt;
        ///                &lt;/td&gt;
        ///              &lt;/tr&gt;
        ///
        ///            &lt;!-- END MAIN CONTENT AREA --&gt;
        ///            &lt;/table&gt;
        ///			&lt;/div&gt;
        ///            &lt;!-- START FOOTER --&gt;
        ///            &lt;div class=&quot;footer&quot; style=&quot;clear: both; Margin-top: 10px; text-align: center; width: 100%;&quot;&gt;
        ///              &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;&quot;&gt;
        ///                &lt;tr&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetailerConfirmationAfterInfo {
            get {
                return ResourceManager.GetString("RetailerConfirmationAfterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Simple Transactional Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///    /* -------------------------------------
        ///        INLINED WITH htmlemail.io/inline
        ///    ------------------------------------- */
        ///    /* -------------------------------------
        ///        RESPONSIVE AND MOBILE FRIENDLY STYLES
        ///    ------------------------------------- */
        ///    @media onl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetailerConfirmationBeforeInfo {
            get {
                return ResourceManager.GetString("RetailerConfirmationBeforeInfo", resourceCulture);
            }
        }
    }
}
